### ISSUE TITLE
1.17

### ISSUE THREAD

**Issue by MenacingPerson** [shedaniel/IronJetpacks#17]
i hate to be this person too man 🤷‍♂️

**Comment by shedaniel** [comment]
Pending jetpack model rendering, this takes time.

**Comment by lmvdz** [comment]
https://github.com/enosich/IronJetpatch/tree/1.17
https://www.curseforge.com/minecraft/mc-mods/iron-jetpatch-fabric

https://user-images.githubusercontent.com/2179775/131178803-b48faf57-925f-46cd-8288-ba36bba325b8.mp4

**Comment by shedaniel** [comment]
Updated
