### ISSUE TITLE
Jetpack charging.

### ISSUE THREAD

**Issue by michlbro** [shedaniel/IronJetpacks#27]
I am still new to this mod, but I have no clue how to power it in fabric. I am currently using a create addon called Crafts and Additions, which adds a tesla coil. This tesla coil is used to charge up FE items. However, when used it does not charge up the jetpacks, but it does work with Industrial Revolutions charging pad (I don't know what energy this uses). I assume this mod will also use FE since it is a port over.

**Comment by shedaniel** [comment]
This mod uses Tech Reborn energy, which is supported by Tech Reborn, Industrial Revolutions, Modern Industrialisations and most other mods. The mod you are using might not be using the de-facto energy api on fabric

**Comment by michlbro** [comment]
Alright thank you.
