### ISSUE TITLE
Crashes CLIENT

### ISSUE THREAD

**Issue by tacogerbil** [shedaniel/IronJetpacks#4]
Minecraft 1.16.4
fabric-api-0.25.4+1.16
cloth-api-1.4.9
Fabric 10.6+b214
---- Minecraft Crash Report ----
// You're mean.

Time: 2020-11-12 11:31:34 PST
Description: Initializing game

java.lang.NoClassDefFoundError: Could not initialize class me.shedaniel.cloth.api.client.events.v0.ClothClientHooks
    at Not Enough Crashes deobfuscated stack trace.(1.16.4+build.6)
    at net.minecraft.client.gui.screen.Screen.handler$bam000$onPreInit(Screen:2618)
    at net.minecraft.client.gui.screen.Screen.init(Screen)
    at net.minecraft.client.MinecraftClient.openScreen(MinecraftClient:922)
    at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:579)
    at net.minecraft.client.main.Main.main(Main:177)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Initialization --

-- System Details --
  Minecraft Version: 1.16.4
  Minecraft Version ID: 1.16.4
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_242, AdoptOpenJDK
  Java VM Version: OpenJDK 64-Bit Server VM (mixed mode),
  Memory: 619306776 bytes (590 MB) / 2044723200 bytes (1950 MB) up to 3817865216 bytes (3641 MB)
  CPUs: 8
  JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms4096m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms256m
  Suspected Mods: Fabric Loader (fabricloader)
  Fabric Mods: accurateblockplacement: Accurate Block Placement 1.0.7
               achaybales: Achaybales 1.3-1.16.4
               adorn: Adorn 1.12.0+1.16.4
               advanced_runtime_resource_pack: Runtime Resource Pack 0.2.6
               advancements-enlarger: Advancements Enlarger 0.2.3
               adventurez: AdventureZ 1.1.3
               amecs: Amecs 1.3.2+mc.1.16.3
               amecsapi: Amecs API 1.1.1+mc1.16-rc1
               angerable-patch: Angerable Patch 1.0.0-1.16.1
               appleskin: AppleSkin 1.0.11
               appliedenergistics2: Applied Energistics 2 8.1.0-alpha.12
               arrfab: Access REI Recipes From A Block 1.0.2+1.16.3
               artifice: Artifice 0.13.2+1.16.3
               authme: Auth Me 1.4.0
               autoconfig1u: Auto Config v1 Updated 3.3.1
               backslot: BackSlot 1.1.7
               backslotaddon: BackSlot Addon 1.0.2
               balance_of_exile: Balance of Exile 1.0.3
               battletowers: Battle Towers 3.2.0-beta-1.16.4
               bebooks: Better Enchanted Books 1.1.4
               bedspreads: Bedspreads 1.2.0-1.16.3
               beenfo: Beenfo 1.16.4-fabric0.25.1-1.2
               bendy-lib: Bendy api 0.2.3
               better_mod_button: Better Mod Button 1.1.4
               better_wandering_trader: Better Wandering Trader 1.6.1
               bettercaves: YUNG's Better Caves 1.16.2-1.0.3
               betterdroppeditems: Better Dropped Items 1.2.4-1.16.2
               betterend: Better End 0.6.1-beta
               betterf3: BetterF3 1.1.1
               betternether: Better Nether 5.0.0
               blackstonetools: Blackstone Tools 1.2.0+1.16.1
               blue_endless_jankson: jankson 1.2.0
               blur: Blur (Fabric) 2.0.0
               bowinfinityfix: Bow Infinity Fix rv9
               bucket-hat: Bucket Hat 1.0.3
               buildersblocks: Builders' Blocks 1.16.3-beta.8
               byg: BYG 1.1.2
               caelus: Caelus API 0.0.9-1.16.3
               camp_fires_cook_mobs: Camp Fires Cook Mobs 1.1.4+MC1.16.2-1.16.4
               can-i-mine-this-block: cAn i MiNe thIS bLOCk? 1.0.2
               cardinal-components-base: Cardinal Components API (base) 2.7.2
               cardinal-components-chunk: Cardinal Components API (chunks) 2.6.0
               cardinal-components-entity: Cardinal Components API (entities) 2.7.2
               cardinal-components-item: Cardinal Components API (items) 2.7.2
               cardinal-components-world: Cardinal Components API (worlds) 2.6.0
               carrier: Carrier 1.4.0
               carvepump: Carve My Pumpkin 1.0.3
               cavebiomes: Cave Biomes 0.5.1
               ce_foodstuffs: Common Expansion: Foodstuffs 1.1.1
               chainmail: Chainmail 0.5.0
               chains: Chains-Link 1.16.2-2.0.1
               chat_heads: Chat Heads 0.2.0+1.16.2
               chunkpregen: Fabric Chunk Pregenerator 0.3.3
               cleardespawn: Clear Despawn 1.16.4-fabric0.25.1-1.1.1
               cloth-api: Cloth API 1.4.9
               cloth-armor-api-v1: Cloth Armor API v1 1.4.9
               cloth-basic-math: Cloth Basic Math 0.5.1
               cloth-client-events-v0: Cloth Client Events v0 1.4.9
               cloth-common-events-v1: Cloth Common Events v1 1.4.9
               cloth-config2: Cloth Config v4 4.8.3
               cloth-datagen-api-v1: Cloth Datagen v1 1.4.9
               cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.4.9
               cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.9
               cloth-scissors-api-v1: Cloth Scissors API v1 1.4.9
               cloth-utils-v1: Cloth Utils v1 1.4.9
               colytra: Colytra 1.2.0-1.16.3
               com_electronwill_night-config_core: core 3.6.0
               com_electronwill_night-config_toml: toml 3.6.0
               com_github_shevek_parallelgzip: parallelgzip master-SNAPSHOT
               com_github_therandomlabs_trlutils-config: TRLUtils-Config master-SNAPSHOT
               com_github_therandomlabs_trlutils-fabric: TRLUtils-Fabric 1.16-SNAPSHOT
               compactstatuseffects: Compact Status Effects 1.2.3
               completeconfig: CompleteConfig 0.5.0
               computercraft: CC:T for Fabric 1.91.2
               cotton-config: Cotton Config 1.0.0-rc.7
               cotton-logging: Cotton Logging 1.0.0-rc.4
               couplings: Couplings 1.3.3
               crawl: Crawl 0.7.5
               crowdin-translate: CrowdinTranslate 1.2
               crumbs: Crumbs 1.0.2+1.16.4-fabric
               curioofundying: Curio of Undying 1.1.0-1.16.3
               curios: Curios API 0.0.10-1.16.3
               curiouselytra: Curious Elytra 1.1.0-1.16.3
               cursed_enchanting: Cursed Enchanting 0.1.3+1.16.1
               curses: Curses 1.5.0
               customstars: Custom Stars 0.4.1
               dankstorage: Dank Storage 1.8c-1.16.3
               darkness: True Darkness 1.6.50
               dawn: Dawn API 1.5.3
               decorative: Decorative 3.0.0
               dungeons_of_exile: Dungeons of Exile 1.1.1
               ears: Ears 1.1.0
               economical_villager_trading: Economical Villager Trading 1.0.2+MC1.16.4
               edit_sign: Edit Sign 2.1.3
               eer: Erroring Entity Remover 1.0.0
               eldritch_mobs: Eldritch Mobs 1.5.1
               emotecraft: Emotecraft 1.2.2
               expandedstorage: ExpandedStorage 5.6.31
               extraorigins: Extra Origins 1.16.4-3
               ezpas: Ezpas 1.2.3-1.16.2
               fabric: Fabric API 0.25.4+1.16
               fabric-api-base: Fabric API Base 0.2.0+9f0fb4b83a
               fabric-biome-api-v1: Fabric Biome API (v1) 3.0.0+8367596d3a
               fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea893a
               fabric-command-api-v1: Fabric Command API (v1) 1.0.9+a4467d2a3a
               fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d308363a
               fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f3a
               fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea8663a
               fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
               fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+f8ac1db23a
               fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b3a
               fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a3a
               fabric-item-api-v1: Fabric Item API (v1) 1.2.0+f8ac1db23a
               fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+a4467d2a3a
               fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c63a
               fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c53a
               fabric-language-kotlin: Fabric Language Kotlin 1.4.0+build.1
               fabric-language-scala: Fabric Language Scala 0.3.2.12
               fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b203a
               fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+432ea1883a
               fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce993a
               fabric-models-v0: Fabric Models (v0) 0.1.1+f8ac1db23a
               fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b3a
               fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5fa7
               fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+a89534ab3a
               fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+a4467d2a3a
               fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e3a
               fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.6.1+a4467d2a3a
               fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.3+a4467d2a3a
               fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+a4467d2a3a
               fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+f8ac1db295
               fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+f8ac1db23a
               fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+f8ac1db23a
               fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+f8ac1db23a
               fabric-rendering-v1: Fabric Rendering (v1) 1.3.1+f8ac1db23a
               fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.1+facf3bbf3a
               fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+872498413a
               fabric-structure-api-v1: Fabric Structure API (v1) 1.1.0+f8ac1db23a
               fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c593a
               fabric-textures-v0: Fabric Textures (v0) 1.0.5+a4467d2a3a
               fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+c93221003a
               fabricloader: Fabric Loader 0.10.6+build.214
               fabricskyboxes: FabricSkyBoxes 0.4.0
               fabrictailor: Fabric Tailor 1.3.1-1.16.4
               fallflyinglib: FallFlyingLib 1.1.0
               falling_tree: FallingTree 2.6.0
               fallingleaves: Falling Leaves 1.1
               fastfurnace: FastFurnace 2.3
               fiber: fiber 0.23.0-1
               fluidtank: Fluid Tank 16.0.7-fabric
               flyring: Ring of Flight 0.1.0+1.16.3
               fullbellysheep: Full Belly Sheep 1.1.0
               gamblers_curse: Curse of The Gambler 0.1.1+1.16.1
               gbfabrictools: GBfabrictools 1.3.1+1.16.4
               glassdoor: Glass Doors 1.5.0-1.16
               glowcase: Glowcase 0.0.10
               golemsgalore: Golems Galore 0.2.0+mc.1.16.2
               harmfulstonecutters: Harmful Stonecutters 1.0.1
               hellish-materials: Hellish Materials 0.12.2
               hookshot: Hookshot 10.0
               hotfurnace: Hot Furnace 1.1.1
               hypnos: Hypnos 0.1.1
               illuminations: Illuminations 1.2.5
               imm_ptl_core: Immersive Portals Core 0.43
               immersive_portals: Immersive Portals 0.43
               improved-stations: Improved Stations 2.0.3
               indrev: Industrial Revolution 1.7.8-BETA
               inmis: Inmis 1.3.1-1.16.2
               invtrashslot: InvTrashSlot 1.0.2
               iron-jetpacks: Iron Jetpacks 0.2.5
               itemmodelfix: Item Model Fix 0.2.4
               jankson: Jankson 3.0.1+j1.2.0
               javax_vecmath_vecmath: vecmath 1.5.2
               kibe: Kibe 1.5.2-BETA
               kirin: Kirin UI 1.7-1.16.2
               kubejs: KubeJS 1.6.0
               lambdabettergrass: LambdaBetterGrass 1.0.1+1.16.3
               lambdynlights: LambDynamicLights 1.3.2+1.16.4
               lapisreserve: Lapis Reserve 1.0.6
               libblockattributes: LibBlockAttributes 0.8.4
               libblockattributes_core: LibBlockAttributes (Core) 0.8.4
               libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.4
               libblockattributes_items: LibBlockAttributes (Items) 0.8.4
               libcd: LibCapableData 3.0.3+1.16.3
               libgui: LibGui 3.2.0+1.16.3
               library_of_exile: Library of Exile 1.0.6
               libstructure: LibStructure 1.5
               lithium: Lithium 0.6.0
               lithium-api: Lithium API 0.6.0
               llamasteeds: Llama Steeds 2020.2.8
               loadcatcher: Entrypoint Catcher 2.0.0
               magna: Magna 1.4.3-1.16.2
               mcdw: MC Dungeons Weapons 1.1.7
               mcpatcherpatcher: MCPatcherPatcher 1.0.0+1.16.2
               medievalweapons: Medieval Weapons 1.0.1
               megane: megane 2.1.0+1.16
               megane-api: megane-api 2.1.0+1.16
               megane-impl: megane-impl 2.1.0+1.16
               megane-runtime: megane-runtime 2.1.0+1.16
               midnight-hats: Midnight Hats 1.0.2
               minecraft: Minecraft 1.16.4
               minecraftcapes: MinecraftCapes Mod 10
               missingbits: Missing Bits v1.16.3 Fabric b1
               mm: Manningham Mills 2.1
               mmorpg: Age of Exile 1.7.6
               mo_glass: Mo Glass 1.5-MC1.16.4
               modify-drops-api: Modify Drops API 0.3.1
               modmenu: Mod Menu 1.14.7+build.11
               mooblooms: Mooblooms 1.3.2
               morebookshelves: Bookshelving 0.0.1
               morecraftingtables: Oh, How the Crafting Has Tabled! 0.1.3-1.16.3
               moretotems: More Totems 2.7.0
               mostructures: Mo' Structures 1.0.0-pre3+mc.1.16.2
               mousewheelie: Mouse Wheelie 1.5.10+mc1.16.4
               mubble: Mubble 4.0-pre6
               nbtcrafting: NBT Crafting 2.0.0-rc.7+mc1.16.2-pre1
               netherite_plus: Netherite Plus Mod 1.1.0
               nicetohave: Nice to Have 1.3.4
               no_sneaking_over_magma: No Sneaking Over Magma! 1.0.5+MC1.16.2-1.16.4
               notenoughcrashes: Not Enough Crashes 2.1.4+1.16.1
               oaktree: Oak Tree 0.4.2-beta
               obsidiplates: Obsidiplates 0.1.1
               olifantenpad: Olifantenpad 1.0.0
               org_apache_commons_commons-compress: commons-compress 1.19
               org_apache_httpcomponents_httpclient: httpclient 4.5.10
               org_apache_httpcomponents_httpcore: httpcore 4.4.12
               org_apache_httpcomponents_httpmime: httpmime 4.5.10
               org_jetbrains_annotations: annotations 20.0.0
               org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.0
               org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.0
               org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.0
               org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.0
               org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.9
               org_tukaani_xz: xz 1.8
               origins: Origins 0.4.4
               origins-classes: Origins: Classes 1.1.0
               paintingcycle: Painting Cycle 1.0.0
               parakeetmod: The Parakeet Mod 1.16.3-1.0.6
               parchment: Parchment 1.0.2+1.15.2
               passable-leaves: Passable Leaves 1.2.3
               patchouli: Patchouli 1.16.2-44-FABRIC
               pconfig: Paradox Config 0.3.6-alpha
               pehkui: Pehkui 1.6.2+1.16.3
               petowner: Pet Owner 1.7.0-1.16.2+
               phosphor: Phosphor 0.6.0+build.7
               pigpoop: Pig Poop 1.1.3
               pinesbarrels: Better Barrels 1.0.1
               plantable_pots: Plantable Flower Pots 0.0.2-SNAPSHOT
               playerabilitylib: Pal 1.2.1
               polymorph: Polymorph 0.0.5-1.16.3
               presencefootsteps: Presence Footsteps r28+1.16.2
               randompatches: RandomPatches 1.16.1-0.0.0.5-fabric
               rare-ice: Rare Ice 0.2.2
               reach-entity-attributes: Reach Entity Attribute 1.0.1
               realistic_bakery_products: Realistic Bakery Products 1.1.5
               reborncore: Reborn Core 4.6.1+build.97
               repurposed_structures: Repurposed Structures 1.16.3-1.6.9
               respawnablepets: Respawnable Pets 1.16.4-1
               retino: retiNO 1.0.0
               rhino: Rhino 1.7.13
               right-click-clear: Right Click Clear 2.0.2
               rotten: FleshZ 1.2.2
               roughlyenoughitems: Roughly Enough Items 5.8.3
               roughlyenoughitems-api: REI (API) 5.8.3
               roughlyenoughitems-default-plugin: REI (Default Plugin) 5.8.3
               roughlyenoughitems-runtime: REI (Runtime) 5.8.3
               sandwichable: Sandwichable 1.1.2
               satin: Satin 1.5.1
               screenshotclipboard: Screenshot to Clipboard 1.0.6
               seasons: Fabric Seasons 0.3-BETA
               skinswapper: Minecraft Skin Change Mod 2.0.1
               smokeextender: Smoke Extender 1.4.0
               sodium: Sodium 0.1.0-SNAPSHOT
               spongesplus: Sponges Plus 1.0.1
               spruceui: SpruceUI 1.6.4
               static-content: Static Content 1.0.1-1.16.2
               staticdata: Static Data 1.1.2
               structure-helpers: Structure Helpers 3.0.0
               structurized: Structurized 1.1.0
               suitablystackablestew: Suitably Stackable Stew 1.1.1
               tacobell: Taco Bell 1.1.1
               tacocraft: TacoCraft 1.3.1+mc.1.16
               team_reborn_energy: Energy 0.1.1
               techreborn: Tech Reborn 3.7.1+build.162
               terraform-tree-api-v1: Terraform Tree API (v1) 1.0.1+build.2
               textile_backup: Textile Backup 2.0.1-1.16.3
               the_loved_ones: The Loved Ones 1.0.0+1.16.1
               tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
               tooltipfix: ToolTip Fix 1.0.2-1.16
               toomanybinds: Too Many Binds 0.3.0+1.16.3
               tweed: Tweed API 3.0.0-beta.20
               uglyscoreboardfix: Ugly Scoreboard Fix 0.2.1
               universalcomponents: Universal Components 0.7.3+1.16.2
               vanilladeathchest: VanillaDeathChest 1.16.3-1.11.0.7-fabric
               varied-mobs: Varied Mobs 0.2.4
               villagerhats: Villager Hats fabric-1.16.4-1.0.1
               villagernames: Villager Names 1.2.5
               voyager: Voyager 1.0.0
               waila: Hwyla 1.9.22
               whereisit: Where Is It 1.9.1
               wi_zoom: WI Zoom 1.3-MC1.16.4
               winged: Winged Mod 1.16.2-1.4.1
               wither_cage_fix: Mod Name 1.0.3+MC1.16.1-1.16.4
               wolveswitharmor: Wolves With Armor 1.5.2-1.16.2
               worldedit: WorldEdit 7.2.0+a51fa43
               xaerominimap: Xaero's Minimap 20.27.2
               xaeroworldmap: Xaero's World Map 1.11.0
  Patchouli open book context: n/a
  Launched Version: 1.16.4
  Backend library: LWJGL version 3.2.2 build 10
  Backend API: GeForce GTX 1070/PCIe/SSE2 GL version 4.6.0 NVIDIA 457.30, NVIDIA Corporation
  GL Caps: Using framebuffer using OpenGL 3.0
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fabric'
  Type: Client (map_client.txt)
  CPU: 8x Intel® Core™ i7-9700K CPU @ 3.60GHz

**Comment by shedaniel** [comment]
install cloth api
